[versions]
[libraries]
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version = "2.0.1" }
resilience4j-circuitbreaker = { module = "io.github.resilience4j:resilience4j-circuitbreaker", version = "1.7.1" }
auth0-jwt = { module = "com.auth0:java-jwt", version = "4.4.0" }
auth0-jwks-rsa = { module = "com.auth0:jwks-rsa", version = "0.22.0" }